"""Loaders for the exported champions-mod data under data/champions/*.json.

Each JSON file is regenerated by `tools/export_champions_data.py` from the Showdown
repo's "champions" mod (the mod backing gen9championsvgc2026regmb) and is checked into
this repo as the format's ground truth. Load through these functions (not by hand) so
every caller shares one cached parse.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from vgc.config import DATA_DIR


def _load_json(filename: str) -> dict[str, Any]:
    path = DATA_DIR / filename
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found -- run `.venv/bin/python tools/export_champions_data.py` "
            "to regenerate data/champions/*.json from the showdown repo"
        )
    with path.open() as file:
        return json.load(file)


@lru_cache(maxsize=1)
def load_species() -> dict[str, Any]:
    """Species keyed by id: stats, types, abilities, mega forme mappings, legality."""
    return _load_json("species.json")


@lru_cache(maxsize=1)
def load_moves() -> dict[str, Any]:
    """Moves keyed by id: power/type/category/accuracy/priority/target/flags/secondary."""
    return _load_json("moves.json")


@lru_cache(maxsize=1)
def load_items() -> dict[str, Any]:
    """LEGAL items only, keyed by id (isNonstandard items are excluded at export time)."""
    return _load_json("items.json")


@lru_cache(maxsize=1)
def load_learnsets() -> dict[str, Any]:
    """Learnsets keyed by species id -> {move_id: [source codes]}."""
    return _load_json("learnsets.json")


@lru_cache(maxsize=1)
def load_typechart() -> dict[str, Any]:
    """Type chart keyed by type id: {name, damageTaken}."""
    return _load_json("typechart.json")


@lru_cache(maxsize=1)
def load_natures() -> dict[str, Any]:
    """Natures keyed by id: {name, plus, minus}."""
    return _load_json("natures.json")


@lru_cache(maxsize=1)
def load_mechanics_catalog() -> dict[str, Any]:
    """Exact legal entities and Showdown mechanics hooks for the target format."""

    return _load_json("mechanics_catalog.json")


@lru_cache(maxsize=1)
def load_mechanics_coverage() -> dict[str, Any]:
    """Reviewed exact/partial/missing status for every mechanics family."""

    return _load_json("mechanics_coverage.json")


def clear_cache() -> None:
    """Drop all cached loads -- mainly useful for tests that re-export data mid-run."""
    load_species.cache_clear()
    load_moves.cache_clear()
    load_items.cache_clear()
    load_learnsets.cache_clear()
    load_typechart.cache_clear()
    load_natures.cache_clear()
    load_mechanics_catalog.cache_clear()
    load_mechanics_coverage.cache_clear()


def data_dir() -> Path:
    return DATA_DIR
