"""Opponent `PokemonState` assembly from a poke-env observed Pokemon.

This format's ladder always runs Open Team Sheets (see `PolicyConfig.
accept_open_team_sheet`, `vgc.agent.VgcPlayer`) -- every opponent Pokemon's
species/moves/item/ability is revealed before team preview, for the whole battle. Stat
Points and nature are NOT part of Open Team Sheets and stay hidden the entire battle;
`opponent_state` fills that gap with real usage-stats data when available
(`load_usage_spreads`) or `vgc.stats.default_opponent_spread`/`default_opponent_nature`
otherwise.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Protocol

from vgc.config import DATA_DIR
from vgc.damage import PokemonState, to_id
from vgc.data import load_learnsets, load_moves, load_species
from vgc.models import PolicyConfig
from vgc.principles import WEATHER_SETTER_ABILITIES, WEATHER_SPEED_ABILITIES
from vgc.stats import SPSpread, default_opponent_nature, default_opponent_spread

# Not committed yet (see CLAUDE.md's data/champions/ note -- this directory is a Phase
# 2a stub, not exported data): a future usage-stats pipeline would populate
# data/usage/spreads.json. load_usage_spreads gracefully no-ops until that exists.
USAGE_DIR = DATA_DIR.parent / "usage"
DEFAULT_USAGE_SPREADS_PATH = USAGE_DIR / "spreads.json"

# Phase 3: per-species move/item/ability frequencies aggregated from the downloaded
# replay corpus by tools/build_set_priors.py -- see load_set_priors/opponent_move_ids
# below. Committed (like spreads.json above), regenerated by rerunning that tool.
DEFAULT_SET_PRIORS_PATH = USAGE_DIR / "set_priors.json"

# poke_env.battle.status.Status member names, lowercased, that are damage-relevant here
# (only "brn" actually changes anything in vgc.damage today, but the others are passed
# through for forward compatibility / other future evaluator logic. "fnt" is dropped --
# a fainted Pokemon isn't a meaningful damage_range() input).
_RECOGNIZED_STATUS_IDS = frozenset({"brn", "par", "psn", "tox", "slp", "frz"})


class ObservedPokemon(Protocol):
    """Structural type for what `opponent_state`/`opponent_move_ids` need -- satisfied
    by poke-env's `Pokemon` (e.g. `DoubleBattle.opponent_active_pokemon_1/_2`, or any
    value from `DoubleBattle.opponent_team`), but written as a Protocol so tests/callers
    can pass a lightweight stand-in without depending on poke-env's constructor.
    """

    species: str
    item: str | None
    ability: str | None
    boosts: dict[str, int]
    status: Any  # poke_env.battle.status.Status | None
    current_hp_fraction: float
    moves: dict[
        str, Any
    ]  # move_id -> poke_env.battle.move.Move (only opponent_move_ids reads this)


@lru_cache(maxsize=8)
def load_usage_spreads(path: str | None = None) -> dict[str, list[dict[str, Any]]]:
    """Load a JSON file of common Stat Point spreads per species:

        {"garchomp": [{"sp": {"hp": 30, "atk": 4, "spe": 32}, "nature": "adamant",
                        "weight": 0.42}, ...], ...}

    `weight` is any relative popularity score (higher = more common); `opponent_state`
    picks the highest-weight entry per species, while `opponent_spread_hypotheses` keeps
    them all as a normalized belief distribution.

    Graceful fallback: if `path` is None, defaults to `data/usage/spreads.json`
    (`DEFAULT_USAGE_SPREADS_PATH`); if that file doesn't exist yet -- there is no usage
    export pipeline as of Phase 2a, this is a stub for a later one -- returns an empty
    dict rather than raising, and every caller falls back to
    `vgc.stats.default_opponent_spread` instead.
    """
    resolved = Path(path) if path is not None else DEFAULT_USAGE_SPREADS_PATH
    if not resolved.exists():
        return {}
    with resolved.open() as file:
        return json.load(file)


def _usage_spread_for_species(
    species_id: str, usage: dict[str, list[dict[str, Any]]]
) -> tuple[SPSpread, str] | None:
    entries = usage.get(species_id)
    if not entries:
        return None
    best = max(entries, key=lambda entry: entry.get("weight", 0))
    return best["sp"], best["nature"]


def opponent_spread_hypotheses(
    species_id: str,
    usage: dict[str, list[dict[str, Any]]] | None = None,
    limit: int | None = None,
) -> list[tuple[SPSpread, str, float]]:
    """Weighted Stat Point/nature beliefs for one opponent species, most likely first.

    `opponent_state` collapses this to its single most popular entry, which is the right
    default for the myopic evaluator's one damage number per matchup. Callers that can
    afford to reason over a DISTRIBUTION -- notably `vgc.rl.live_mirror`, which can build
    one Showdown root per hypothesis -- should use this instead, so "probably Adamant"
    stays a probability instead of hardening into a fact.

    Probabilities are renormalized over whatever survives `limit`, so the returned
    weights always sum to 1.0. A species with no usage data yields exactly one
    hypothesis, `vgc.stats.default_opponent_spread`/`default_opponent_nature` at
    probability 1.0 -- a certain belief, because there is nothing to be uncertain
    between, not because that spread is known to be right.
    """
    if limit is not None and limit < 1:
        raise ValueError(f"limit must be at least 1, got {limit!r}")
    if usage is None:
        usage = load_usage_spreads()
    entries = usage.get(species_id) or []
    ranked = sorted(
        (entry for entry in entries if entry.get("sp") is not None),
        key=lambda entry: (-float(entry.get("weight", 0.0)), str(entry.get("nature", ""))),
    )
    if limit is not None:
        ranked = ranked[:limit]
    total = sum(max(0.0, float(entry.get("weight", 0.0))) for entry in ranked)
    if not ranked or total <= 0.0:
        return [
            (
                default_opponent_spread(species_id),
                default_opponent_nature(species_id),
                1.0,
            )
        ]
    return [
        (
            entry["sp"],
            entry["nature"],
            max(0.0, float(entry.get("weight", 0.0))) / total,
        )
        for entry in ranked
    ]


@lru_cache(maxsize=8)
def load_set_priors(path: str | None = None) -> dict[str, Any]:
    """Load `data/usage/set_priors.json` (see `tools/build_set_priors.py`): per-species
    move/item/ability frequencies plus an `"appearances"` count, aggregated from the
    downloaded replay corpus --

        {"meta": {...}, "species": {"garchomp": {"appearances": 812,
            "moves": {"protect": 640, "earthquake": 705, ...},
            "items": {"lifeorb": 210, ...}, "abilities": {"roughskin": 800, ...}},
            ...}}

    Graceful fallback: if `path` is None, defaults to `DEFAULT_SET_PRIORS_PATH`; if that
    file doesn't exist yet, returns `{}` rather than raising -- same contract as
    `load_usage_spreads` above, and every caller (`opponent_move_ids`) treats a missing/
    unknown-species entry as "no prior available, use only what's actually revealed".
    """
    resolved = Path(path) if path is not None else DEFAULT_SET_PRIORS_PATH
    if not resolved.exists():
        return {}
    with resolved.open() as file:
        return json.load(file)


def usage_spreads_for(config: PolicyConfig) -> dict[str, list[dict[str, Any]]]:
    """`load_usage_spreads` for the file `config.usage_spreads_file` names in data/usage/."""
    return load_usage_spreads(str(USAGE_DIR / config.usage_spreads_file))


def set_priors_for(config: PolicyConfig) -> dict[str, Any]:
    """`load_set_priors` for the file `config.set_priors_file` names in data/usage/."""
    return load_set_priors(str(USAGE_DIR / config.set_priors_file))


def opponent_move_ids(
    pokemon: ObservedPokemon,
    priors: dict[str, Any] | None = None,
    config: PolicyConfig | None = None,
) -> list[str]:
    """Revealed move ids (from `pokemon.moves`, `to_id`-normalized) PLUS, when fewer
    than `config.set_prior_max_moves` are revealed and `config.use_set_priors` is set,
    the highest-frequency prior moves for that species (from `load_set_priors()`'s
    corpus-derived frequencies) that aren't already revealed -- filled up to
    `set_prior_max_moves` total, ranked by raw appearance count (ties broken by id for
    determinism). Only trusts a species' priors once it has at least
    `config.set_prior_min_games` tracked appearances (`load_set_priors`'s
    `"appearances"` field) -- below that the sample is too thin to distinguish a real
    trend from noise, and this function silently falls back to revealed-only.

    A prior move id that turns out to not be in `data/champions/moves.json` (or isn't
    otherwise usable downstream) is NOT filtered out here -- `vgc.damage.damage_range`
    already reports an unsupported/unknown move via `breakdown["move_supported"] =
    False` rather than crashing, so a slightly noisy prior entry just contributes 0 to a
    damage-based computation instead of breaking anything that reads this list.

    :param priors: pre-loaded `load_set_priors()` result to reuse across many calls
        (avoids re-reading the file per Pokemon, mirroring `opponent_state`'s own
        `usage=` parameter); `None` loads the default path (cheap after the first call
        -- `load_set_priors` is `lru_cache`d).
    """
    config = config or PolicyConfig()
    revealed = [move_id for move_id in (to_id(raw) for raw in (pokemon.moves or {})) if move_id]

    if not config.use_set_priors or len(revealed) >= config.set_prior_max_moves:
        return revealed

    if priors is None:
        priors = set_priors_for(config)
    species_id = to_id(pokemon.species)
    entry = (priors.get("species") or {}).get(species_id) if priors else None
    if not entry or entry.get("appearances", 0) < config.set_prior_min_games:
        if not config.set_prior_learnset_fallback:
            return revealed
        filled = list(revealed)
        for move_id in learnset_fallback_move_ids(species_id):
            if len(filled) >= config.set_prior_max_moves:
                break
            if move_id not in filled:
                filled.append(move_id)
        return filled

    revealed_set = set(revealed)
    move_counts: dict[str, int] = entry.get("moves") or {}
    ranked = sorted(move_counts.items(), key=lambda item: (-item[1], item[0]))

    filled = list(revealed)
    for move_id, _count in ranked:
        if len(filled) >= config.set_prior_max_moves:
            break
        if move_id in revealed_set:
            continue
        filled.append(move_id)
        revealed_set.add(move_id)
    return filled


# Legal damaging moves that are poor stand-ins for "what this Pokemon hits us with this
# turn": only usable on the first turn out, only while asleep, land turns later, fail
# when the user is hit first, faint the user, or need a precondition this state-free guess cannot check
# (terrain, a consumed Berry, other moves used first, a foe's priority move).
# Recharge/charge-turn moves are excluded by their data flags.
_FALLBACK_EXCLUDED_MOVES = frozenset(
    {
        "fakeout",
        "firstimpression",
        "focuspunch",
        "snore",
        "sleeptalk",
        "dreameater",
        "futuresight",
        "doomdesire",
        "steelroller",
        "belch",
        "lastresort",
        "upperhand",
        "explosion",
        "selfdestruct",
        "mistyexplosion",
    }
)


@lru_cache(maxsize=512)
def learnset_fallback_move_ids(species_id: str) -> tuple[str, ...]:
    """Best guess at a no-prior species' attacks, from its Champions learnset alone.

    Used by `opponent_move_ids` when a species has no usable corpus prior (the checked-in
    priors are M-B-era and miss much of M-C -- Rillaboom, Salamence, Indeedee-F...). An
    empty list there made the search treat a full-HP attacker as harmless. This returns
    the strongest legal damaging move of each of the species' OWN types (STAB only),
    ordered by base power x the matching base attacking stat x accuracy -- at most two.

    Deliberately not "best move of every type": that version gave each unknown foe four
    strong attacks of four types, i.e. perfect coverage no real set has, and the bot
    answered by Protecting ~4.7x as often (same-session A/B on the six mc_ladder teams:
    5.5% on mc_ladder_04). It is a threat estimate, not a set prediction: no utility
    moves (Fake Out, Protect, Tailwind), items/abilities ignored. Mega/alternate formes
    without their own learnset use the base species'.
    """

    species = load_species()
    data = species.get(species_id) or {}
    learnsets = load_learnsets()
    learnset = learnsets.get(species_id) or learnsets.get(to_id(data.get("baseSpecies"))) or {}
    types = set(data.get("types") or ())
    base_stats = data.get("baseStats") or {}
    moves = load_moves()
    best_by_type: dict[str, tuple[float, str]] = {}
    for move_id in learnset:
        move = moves.get(move_id)
        if move is None or move.get("isNonstandard") is not None:
            continue
        if move["category"] == "Status" or move_id in _FALLBACK_EXCLUDED_MOVES:
            continue
        flags = move.get("flags") or {}
        base_power = int(move.get("basePower") or 0)
        if base_power <= 0 or flags.get("recharge") or flags.get("charge"):
            continue
        stat = base_stats.get("atk" if move["category"] == "Physical" else "spa", 0)
        accuracy = move.get("accuracy")
        # `accuracy: true` means it never misses; bool is an int, so check it first.
        hit = (
            1.0 if accuracy is True or not isinstance(accuracy, (int, float)) else accuracy / 100.0
        )
        if move.get("type") not in types:
            continue
        score = base_power * stat * hit
        current = best_by_type.get(move["type"])
        if current is None or (score, move_id) > current:
            best_by_type[move["type"]] = (score, move_id)
    ranked = sorted(best_by_type.values(), key=lambda row: (-row[0], row[1]))
    return tuple(move_id for _score, move_id in ranked)


@dataclass(frozen=True)
class HiddenSetGuess:
    """What `vgc.principles.detect_team_signals`/`classify_mon` read (species, ability,
    moves), with the opponent's hidden parts filled in. Only for plan/role detection --
    never a `PokemonState`, so a guessed ability never reaches the damage calculator.
    """

    species: str
    ability: str | None
    moves: dict[str, None]


def opponent_signal_team(
    pokemon: list[ObservedPokemon],
    priors: dict[str, Any] | None = None,
    config: PolicyConfig | None = None,
) -> list[HiddenSetGuess]:
    """The opponent's team as `detect_team_signals` should see it when sheets are hidden.

    On the ladder a previewed Pokemon has no moves and usually no ability, so reading it
    raw finds no Trick Room, Tailwind or weather plan on any team. Moves come from
    `opponent_move_ids` (revealed first, then set priors). The ability is the revealed
    one, else `_likely_ability` -- a team-level guess, because a weather abuser's
    ability is only worth assuming when a teammate sets that weather.
    """
    config = config or PolicyConfig()
    if priors is None:
        priors = set_priors_for(config)
    species_ids = [to_id(mon.species) for mon in pokemon]
    revealed = [to_id(getattr(mon, "ability", None)) or None for mon in pokemon]
    candidates = [
        _ability_candidates(species_id, normalize_item(getattr(mon, "item", None)), priors, config)
        for species_id, mon in zip(species_ids, pokemon)
    ]

    abilities = list(revealed)
    for idx, ability in enumerate(abilities):
        if ability is None:
            abilities[idx] = _only_or_setter(candidates[idx])
    set_weathers = {
        WEATHER_SETTER_ABILITIES[ability]
        for ability in abilities
        if ability in WEATHER_SETTER_ABILITIES
    }
    for idx, ability in enumerate(abilities):
        if ability is not None:
            continue
        abusers = sorted(
            candidate
            for candidate in candidates[idx]
            if WEATHER_SPEED_ABILITIES.get(candidate) in set_weathers
        )
        if abusers:
            abilities[idx] = abusers[0]

    return [
        HiddenSetGuess(
            species=species_id,
            ability=ability,
            moves=dict.fromkeys(opponent_move_ids(mon, priors=priors, config=config)),
        )
        for species_id, ability, mon in zip(species_ids, abilities, pokemon)
    ]


def _ability_candidates(
    species_id: str, item: str | None, priors: dict[str, Any], config: PolicyConfig
) -> frozenset[str]:
    """Legal abilities of the species, plus its Mega form's when it holds that Mega stone:
    the revealed item if there is one, else the corpus's usual item for the species
    (Charizard -> Charizardite Y -> Charizard-Mega-Y's Drought).
    """
    species = load_species()
    data = species.get(species_id) or {}
    abilities = {to_id(name) for name in (data.get("abilities") or {}).values()}

    stone = to_id(item) if item else None
    if stone is None:
        entry = (priors.get("species") or {}).get(species_id) if priors else None
        items = (entry or {}).get("items") or {}
        if items and (entry or {}).get("appearances", 0) >= config.set_prior_min_games:
            top_item, top_count = max(items.items(), key=lambda item: (item[1], item[0]))
            if top_count >= config.set_prior_min_games:
                stone = top_item
    for forme_name in data.get("otherFormes") or ():
        forme = species.get(to_id(forme_name)) or {}
        if stone and forme.get("isMega") and to_id(forme.get("requiredItem")) == stone:
            abilities |= {to_id(name) for name in (forme.get("abilities") or {}).values()}
    return frozenset(filter(None, abilities))


def _only_or_setter(candidates: frozenset[str]) -> str | None:
    """The ability when only one is possible; else a weather setter's weather ability,
    because a team brings a setter for its weather. Anything else stays unknown.
    """
    if len(candidates) == 1:
        return next(iter(candidates))
    setters = sorted(candidates & WEATHER_SETTER_ABILITIES.keys())
    return setters[0] if setters else None


def normalize_item(item: str | None) -> str | None:
    # poke-env uses the sentinel string "unknown_item" (GenData.UNKNOWN_ITEM) before an
    # item is revealed; under Open Team Sheets this shouldn't linger past team preview,
    # but handle it defensively anyway. Public (not just for opponent_state) since
    # vgc.evaluator reuses it for our own Pokemon's item field too.
    if not item or item == "unknown_item":
        return None
    return item


def normalize_status(status: Any) -> str | None:
    # Public for the same reason as normalize_item -- vgc.evaluator builds PokemonStates
    # for our own side (poke-env Status enum) with the same normalization rules as
    # opponent_state uses for theirs.
    if status is None:
        return None
    status_id = getattr(status, "name", str(status)).lower()
    return status_id if status_id in _RECOGNIZED_STATUS_IDS else None


# Backwards-compatible private aliases (this module's own code below used the
# underscore-prefixed names before they were made public for vgc.evaluator's reuse).
_normalize_item = normalize_item
_normalize_status = normalize_status


# --- Mega Evolution form detection -------------------------------------------------------
#
# poke-env applies a Mega Evolution WITHOUT renaming the Pokemon: `Pokemon.mega_evolve` and
# `forme_change` (the `|-mega|` / `|detailschange|` handlers) load the Mega's dex entry with
# `store_species=False`. So for an opponent that has Mega Evolved, `pokemon.species` is still
# the BASE species while `base_stats`/types are the Mega's and `forme_change_ability` is set.
# Building a `PokemonState` from `pokemon.species` therefore modelled such a Pokemon with
# the base stats and types but the Mega ability. (Our own side usually recovers: the next
# `|request|` carries "<Species>-Mega" details, which does rename `_species`.) The helpers
# below recover the Mega forme from the evidence poke-env keeps, with the exported
# `data/champions/species.json` as the source of truth for stats/ability.


def _text(value: Any) -> str:
    """`to_id` that tolerates a missing/non-string attribute (test stubs, mocks)."""

    return (to_id(value) or "") if isinstance(value, str) else ""


@lru_cache(maxsize=1)
def _mega_formes_by_origin() -> dict[str, tuple[str, ...]]:
    """Mega forme ids keyed by the exact forme they evolve from (`changesFrom`).

    Keyed on `changesFrom`, not on the base species' `otherFormes`: the latter lists every
    Mega on the base (Meowstic-F-Mega under Meowstic) while only Floette-Eternal,
    Meowstic-F, Tatsugiri-Droopy, Magearna-Original, ... have the right to theirs.
    """

    index: dict[str, list[str]] = {}
    for forme_id, data in load_species().items():
        if data.get("isMega"):
            origin = to_id(data.get("changesFrom")) or to_id(data.get("baseSpecies"))
            index.setdefault(origin or "", []).append(forme_id)
    return {origin: tuple(sorted(formes)) for origin, formes in index.items()}


def mega_forme_ids(species_id: str) -> tuple[str, ...]:
    """Ids of every Mega forme `species_id` can evolve into (empty if none)."""

    return _mega_formes_by_origin().get(species_id, ())


def mega_species_id(base_species_id: str, item_id: str | None) -> str | None:
    """The mega forme's species id if `base_species_id` holding `item_id` can mega
    evolve into one (a Mega whose `changesFrom` is that forme), else None. Pure lookup over
    `vgc.data.load_species()` -- no battle state involved.
    """
    if not item_id:
        return None
    for forme_id in mega_forme_ids(base_species_id):
        if to_id(load_species()[forme_id].get("requiredItem")) == item_id:
            return forme_id
    return None


def evolved_mega_id(pokemon: Any) -> str | None:
    """The Mega forme `pokemon` has already Mega Evolved into, else None.

    Evidence, in order: (1) poke-env already stores the Mega species (our own side after the
    next request, or an opponent that switched back in as "<Species>-Mega"); (2) the Pokemon's
    species has Mega formes in `species.json` AND poke-env records a forme change into one
    (`forme_change_ability` is set only for Mega/Primal/Tera-type forme changes) or its
    `base_stats` differ from the base species' and equal a Mega's. When a species has
    several Megas (Charizard X/Y, Garchomp, ...) the candidates are narrowed by the held
    stone, then by matching base stats, then by the forme-change ability, each step applied
    only if it leaves at least one candidate (poke-env's vanilla Mega abilities disagree
    with the Champions mod for a few species, so ability alone is not trusted).
    """

    species_id = _text(getattr(pokemon, "species", None))
    all_species = load_species()
    species = all_species.get(species_id)
    if species is None:
        return None
    if species.get("isMega"):
        return species_id
    candidates = list(mega_forme_ids(species_id))
    if not candidates:
        return None

    stats = getattr(pokemon, "base_stats", None)
    stats = dict(stats) if isinstance(stats, dict) else None
    stat_matches: list[str] = []
    if stats and stats != species.get("baseStats"):
        stat_matches = [c for c in candidates if all_species[c].get("baseStats") == stats]
    forme_ability = _text(getattr(pokemon, "forme_change_ability", None))
    if not forme_ability and not stat_matches:
        return None

    item_id = _text(getattr(pokemon, "item", None))

    def narrow(options: list[str], keep) -> list[str]:
        return [c for c in options if keep(c)] or options

    pool = narrow(
        candidates,
        lambda c: bool(item_id) and to_id(all_species[c].get("requiredItem")) == item_id,
    )
    pool = narrow(pool, lambda c: c in stat_matches)
    pool = narrow(
        pool,
        lambda c: bool(forme_ability)
        and to_id((all_species[c].get("abilities") or {}).get("0")) == forme_ability,
    )
    return pool[0]


def pre_mega_species_id(species_id: str) -> str:
    """The forme a Mega forme evolves from (`charizardmegay` -> `charizard`); any other id is
    returned unchanged. For comparing a Mega-evolved `PokemonState` against ids keyed by the
    pre-evolution species (team-preview gameplan, `BattleMemory.plan_breakers`).
    """

    data = load_species().get(species_id) or {}
    return (to_id(data.get("changesFrom")) or species_id) if data.get("isMega") else species_id


def live_form(
    pokemon: Any, ability: str | None, item: str | None
) -> tuple[str, str | None, str | None]:
    """`(species_id, ability, item)` of the form `pokemon` is in right now.

    Identity for a Pokemon that has not Mega Evolved. After a Mega Evolution the species is
    the Mega forme (so stats and types are the Mega's, from `species.json`), the ability is
    the Mega's unless poke-env tracks a later temporary override (Skill Swap, Mummy, ...),
    and an unrevealed item becomes the Mega's required stone (`|-mega|` made it public).
    """

    species_id = _text(getattr(pokemon, "species", None))
    mega_id = evolved_mega_id(pokemon)
    if mega_id is None:
        return species_id, ability, item
    mega = load_species().get(mega_id) or {}
    if not _text(getattr(pokemon, "temporary_ability", None)):
        mega_ability = to_id((mega.get("abilities") or {}).get("0"))
        if mega_ability:
            ability = mega_ability
    if item is None:
        item = to_id(mega.get("requiredItem")) or None
    return mega_id, ability, item


def opponent_state(
    pokemon: ObservedPokemon,
    usage: dict[str, list[dict[str, Any]]] | None = None,
    nature_override: str | None = None,
    evolved_form: bool = True,
) -> PokemonState:
    """Build a `PokemonState` for an opponent Pokemon observed through poke-env.

    :param pokemon: e.g. `battle.opponent_active_pokemon_1`/`_2`
        (`poke_env.battle.double_battle.DoubleBattle`) or any value from
        `battle.opponent_team`.
    :param usage: pre-loaded `load_usage_spreads()` result to reuse across many calls
        (avoids re-reading the file per Pokemon); `None` loads the default path (cheap
        after the first call -- `load_usage_spreads` is `lru_cache`d).
    :param nature_override: a higher-confidence hidden nature from an exactly recognized
        curated team. The live Open Team Sheet still supplies item/ability/moves; this
        only fills information the sheet does not reveal.
    :param evolved_form: model a Pokemon that has Mega Evolved as its Mega forme (see
        `live_form`); False is the legacy behaviour
        (`PolicyConfig.mega_state_uses_evolved_form`).
    """
    if usage is None:
        usage = load_usage_spreads()

    # Hidden spreads are keyed on poke-env's own species id (the base species until the
    # Pokemon is re-parsed as "<Species>-Mega"); the STATE, though, must be the Mega forme
    # once it has Mega Evolved -- see `live_form`.
    spread_species_id = pokemon.species
    spread_and_nature = _usage_spread_for_species(spread_species_id, usage)
    if spread_and_nature is not None:
        sp_spread, nature = spread_and_nature
    else:
        sp_spread = default_opponent_spread(spread_species_id)
        nature = default_opponent_nature(spread_species_id)
    if nature_override is not None:
        nature = nature_override

    boosts = {
        stat: value
        for stat, value in (pokemon.boosts or {}).items()
        if stat in ("atk", "def", "spa", "spd", "spe") and value
    }

    species_id, ability, item = pokemon.species, pokemon.ability or None, _normalize_item(
        pokemon.item
    )
    if evolved_form:
        species_id, ability, item = live_form(pokemon, ability, item)
    state = PokemonState(
        species_id=species_id,
        sp_spread=sp_spread,
        nature=nature,
        boosts=boosts,
        status=_normalize_status(pokemon.status),
        item=item,
        ability=ability,
    )
    # poke-env reports current_hp/max_hp for OPPONENT Pokemon on a 0-100 or pixel scale,
    # not real Champions HP (see poke_env.battle.pokemon.Pokemon.current_hp's own
    # docstring) -- current_hp_fraction is the scale-independent number, so rescale
    # against our own computed max_hp instead of trusting pokemon.current_hp directly.
    fraction = getattr(pokemon, "current_hp_fraction", 1.0) or 0.0
    state.current_hp = round(state.max_hp() * fraction)
    return state
